services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tuistream_app
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www
      - ./docker/php/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini:ro
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_CONNECTION=pgsql
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_DATABASE=tuistream
      - DB_USERNAME=tuistream
      - DB_PASSWORD=${DB_PASS:?Error: DB_PASS no definida. Ejecute primero install.sh o defina la variable.}
      - REDIS_HOST=redis
    depends_on:
      - postgres
      - redis
    networks:
      - tuistream_net

  postgres:
    image: postgres:17-alpine
    container_name: tuistream_postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: tuistream
      POSTGRES_USER: tuistream
      POSTGRES_PASSWORD: ${DB_PASS:?Error: DB_PASS no definida. Ejecute primero install.sh o defina la variable.}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - tuistream_net

  redis:
    image: redis:7-alpine
    container_name: tuistream_redis
    restart: unless-stopped
    ports:
      - "6380:6379"
    volumes:
      - redisdata:/data
    networks:
      - tuistream_net

  nginx-rtmp:
    image: tiangolo/nginx-rtmp:latest
    container_name: tuistream_nginx_rtmp
    restart: unless-stopped
    ports:
      - "9011:1935"
      - "8085:80"
    volumes:
      - ./docker/nginx-rtmp/nginx.conf:/etc/nginx/nginx.conf:ro
      - hlsdata:/var/hls
    networks:
      - tuistream_net

  icecast:
    image: libretime/icecast:2.5.0
    container_name: tuistream_icecast
    restart: unless-stopped
    ports:
      - "8100:8000"
    volumes:
      - ./docker/icecast/icecast.xml:/etc/icecast.xml:ro
    networks:
      - tuistream_net

  shoutcast:
    image: khartool/shoutcast-x64:2.6.1.777-3.19.1
    container_name: tuistream_shoutcast
    restart: unless-stopped
    ports:
      - "8005:8000"
    volumes:
      - ./docker/shoutcast/sc_serv.conf:/opt/shoutcast/sc_serv.conf:ro
    networks:
      - tuistream_net

  liquidsoap:
    image: savonet/liquidsoap:v2.2.5
    container_name: tuistream_liquidsoap
    restart: unless-stopped
    ports:
      - "8015:8015"
    volumes:
      - ./docker/liquidsoap/script.liq:/etc/liquidsoap/script.liq:ro
      - media:/usr/share/liquidsoap/media
    depends_on:
      - icecast
    networks:
      - tuistream_net

networks:
  tuistream_net:
    driver: bridge

volumes:
  pgdata:
  redisdata:
  hlsdata:
  media:

